# Use https://travis-ci.org/ for automatic tests

# speed up testing https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure/
sudo: false

# This is a java project
language: java

# We run on 8
jdk: [oraclejdk8]

if [ -n \"$GITHUB_API_KEY\" ]; then
  cd \"$TRAVIS_BUILD_DIR\"
  ls

before_deploy:
  - export RELEASE_JAR_FILE=$(ls *.jar)
  - echo "Deploying-> $RELEASE_JAR_FILE to GitHub"
  
deploy:
  provider: releases
  api_key: ${GITHUB_API_KEY}
  file: ${RELEASE_JAR_FILE}
  skip_cleanup: true
